import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { execFileSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const standaloneRoot = path.resolve(scriptDir, "..");
const monorepoRoot = path.resolve(scriptDir, "../../..");
const contractsRoot = fs.existsSync(path.join(standaloneRoot, "src/SubArcFactory.sol"))
  ? standaloneRoot
  : path.join(monorepoRoot, "packages/contracts");
const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), "subarc-abi-"));

execFileSync(
  "npx",
  [
    "--yes",
    "solc@0.8.24",
    "--base-path",
    contractsRoot,
    "--include-path",
    contractsRoot,
    "--abi",
    path.join(contractsRoot, "src/SubArcFactory.sol"),
    "-o",
    tempDir,
  ],
  { stdio: "inherit" }
);

const factoryAbi = readAbi("src_SubArcFactory_sol_SubArcFactory.abi");
const subscriptionAbi = readAbi("src_SubArcSubscription_sol_SubArcSubscription.abi");

writeJson(path.join(contractsRoot, "abi/SubArcFactory.json"), factoryAbi);
writeJson(path.join(contractsRoot, "abi/SubArcSubscription.json"), subscriptionAbi);

writeTsIfDirExists(path.join(monorepoRoot, "apps/hub/src/lib/generatedAbis.ts"), {
  SUBARC_FACTORY_V1_ABI: factoryAbi,
  SUBARC_LOGIC_V1_ABI: subscriptionAbi,
});
writeTsIfDirExists(path.join(monorepoRoot, "packages/sdk/src/abis.ts"), {
  subArcFactoryAbi: factoryAbi,
  subArcSubscriptionAbi: subscriptionAbi,
});

console.log("Generated SubArc ABI artifacts");

function readAbi(fileName) {
  return JSON.parse(fs.readFileSync(path.join(tempDir, fileName), "utf8"));
}

function writeJson(target, value) {
  fs.mkdirSync(path.dirname(target), { recursive: true });
  fs.writeFileSync(target, `${JSON.stringify(value, null, 2)}\n`);
}

function writeTsIfDirExists(target, exports) {
  if (!fs.existsSync(path.dirname(target))) return;
  fs.mkdirSync(path.dirname(target), { recursive: true });
  const body = Object.entries(exports)
    .map(([name, value]) => `export const ${name} = ${JSON.stringify(value, null, 2)} as const;`)
    .join("\n\n");
  fs.writeFileSync(
    target,
    `// Generated by packages/contracts/scripts/generate-abis.mjs\n// Do not edit manually.\n\n${body}\n`
  );
}
